"""Reads the committed word lists in app/data/wordlists and turns them into
the day's Spelling Bee and Word Ladder.

Everything here is deterministic and offline. The files are generated by
scripts/build_wordlists.py, which enumerates only puzzles it has already
proven playable — a Bee whose letters come from a real pangram and yield
8-40 valid words, a Ladder pair with a genuine 3-6 step path — so selection
is a lookup, not a generation with a chance of failing.

Puzzles are chosen by date ordinal. The generated files are shuffled at build
time precisely so this walk doesn't serve near-identical puzzles on
consecutive days, and both are large enough to run for years without
repeating: ~3,000 Bee puzzles and 4,000 Ladder pairs.
"""
from __future__ import annotations

import logging
from datetime import date
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "wordlists"

# Bee word lists are recomputed per puzzle from this pool, rather than stored
# per puzzle, because the pool is one 338 KB file whereas ~3,000 expanded word
# lists would be several megabytes of near-duplicate data.
BEE_MIN_LENGTH = 4


def _read(name: str) -> list[str]:
    return [
        line
        for line in (DATA_DIR / name).read_text().splitlines()
        if line and not line.startswith("#")
    ]


@lru_cache(maxsize=1)
def _bee_answers() -> frozenset[str]:
    return frozenset(_read("bee_answers.txt"))


@lru_cache(maxsize=1)
def _bee_puzzles() -> tuple[tuple[str, str], ...]:
    return tuple((row.split()[0], row.split()[1]) for row in _read("bee_puzzles.txt"))


@lru_cache(maxsize=1)
def _ladder_words() -> tuple[str, ...]:
    return tuple(_read("ladder_words.txt"))


@lru_cache(maxsize=1)
def _ladder_puzzles() -> tuple[tuple[str, str, int], ...]:
    rows = (row.split() for row in _read("ladder_puzzles.txt"))
    return tuple((start, target, int(steps)) for start, target, steps in rows)


def bee_words(pangram: str, centre: str) -> list[str]:
    """Every valid answer for these seven letters, longest first so the
    pangram tends to lead."""
    letters = set(pangram)
    words = [
        word.upper()
        for word in _bee_answers()
        if len(word) >= BEE_MIN_LENGTH and centre in word and set(word) <= letters
    ]
    return sorted(words, key=lambda word: (-len(word), word))


def spelling_bee_for(puzzle_date: date) -> tuple[list[str], str, list[str]]:
    """(7 letters, centre letter, valid words) for the given day."""
    puzzles = _bee_puzzles()
    pangram, centre = puzzles[puzzle_date.toordinal() % len(puzzles)]
    return sorted(letter.upper() for letter in set(pangram)), centre.upper(), bee_words(pangram, centre)


def word_ladder_for(puzzle_date: date) -> tuple[str, str, list[str], int]:
    """(start, target, allowed words, true optimal steps) for the day.

    `allowed_words` is the whole 4-letter pool, not a shortlist. The client
    treats it as a hidden whitelist — DailyGamesViewModels.submit() rejects
    anything outside it with "That word isn't in today's ladder" and never
    shows the player what is in it — so anything less than the full pool
    rejects ordinary English words for no reason the player can see. A
    12-word bank turned FIGS -> FINS -> FINE into an error even though every
    one of those is a real word one letter apart, and FINE -> FILE -> FILM
    finishes the puzzle.

    Handing over the entire component also keeps the stored optimum honest:
    it was computed by BFS over exactly this pool at build time, so it stays
    the true shortest path over what the player is allowed to type.
    """
    puzzles = _ladder_puzzles()
    start, target, steps = puzzles[puzzle_date.toordinal() % len(puzzles)]
    return start.upper(), target.upper(), [word.upper() for word in _ladder_words()], steps


def available() -> bool:
    """False if the data files didn't ship, so callers can fall back rather
    than fail the whole day's games."""
    try:
        return bool(_bee_puzzles()) and bool(_ladder_puzzles()) and bool(_bee_answers())
    except OSError as exc:
        logger.warning("Word list data unavailable: %s", exc)
        return False
