"""Reads the committed word lists in app/data/wordlists and turns them into
the day's Spelling Bee and Word Ladder.

Everything here is deterministic and offline. The files are generated by
scripts/build_wordlists.py, which enumerates only puzzles it has already
proven playable — a Bee whose letters come from a real pangram and yield
8-40 valid words, a Ladder pair with a genuine 3-6 step path — so selection
is a lookup, not a generation with a chance of failing.

Puzzles are chosen by date ordinal. The generated files are shuffled at build
time precisely so this walk doesn't serve near-identical puzzles on
consecutive days, and both are large enough to run for years without
repeating: ~3,000 Bee puzzles and 4,000 Ladder pairs.
"""
from __future__ import annotations

import logging
from collections import deque
from datetime import date
from functools import lru_cache
from pathlib import Path
from string import ascii_lowercase

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "wordlists"

# Bee word lists are recomputed per puzzle from this pool, rather than stored
# per puzzle, because the pool is one 338 KB file whereas ~3,000 expanded word
# lists would be several megabytes of near-duplicate data.
BEE_MIN_LENGTH = 4

# _validate_ladder accepts 6-15 allowed words; the client renders them as a
# word bank, so this stays comfortably inside that range.
LADDER_BANK_SIZE = 12


def _read(name: str) -> list[str]:
    return [
        line
        for line in (DATA_DIR / name).read_text().splitlines()
        if line and not line.startswith("#")
    ]


@lru_cache(maxsize=1)
def _bee_answers() -> frozenset[str]:
    return frozenset(_read("bee_answers.txt"))


@lru_cache(maxsize=1)
def _bee_puzzles() -> tuple[tuple[str, str], ...]:
    return tuple((row.split()[0], row.split()[1]) for row in _read("bee_puzzles.txt"))


@lru_cache(maxsize=1)
def _ladder_words() -> tuple[str, ...]:
    return tuple(_read("ladder_words.txt"))


@lru_cache(maxsize=1)
def _ladder_puzzles() -> tuple[tuple[str, str, int], ...]:
    rows = (row.split() for row in _read("ladder_puzzles.txt"))
    return tuple((start, target, int(steps)) for start, target, steps in rows)


def bee_words(pangram: str, centre: str) -> list[str]:
    """Every valid answer for these seven letters, longest first so the
    pangram tends to lead."""
    letters = set(pangram)
    words = [
        word.upper()
        for word in _bee_answers()
        if len(word) >= BEE_MIN_LENGTH and centre in word and set(word) <= letters
    ]
    return sorted(words, key=lambda word: (-len(word), word))


def spelling_bee_for(puzzle_date: date) -> tuple[list[str], str, list[str]]:
    """(7 letters, centre letter, valid words) for the given day."""
    puzzles = _bee_puzzles()
    pangram, centre = puzzles[puzzle_date.toordinal() % len(puzzles)]
    return sorted(letter.upper() for letter in set(pangram)), centre.upper(), bee_words(pangram, centre)


def _shortest_path(start: str, target: str, pool: set[str]) -> list[str]:
    """One shortest start->target path, inclusive of both ends."""
    previous: dict[str, str | None] = {start: None}
    queue = deque([start])
    while queue:
        word = queue.popleft()
        if word == target:
            break
        for index in range(len(word)):
            for char in ascii_lowercase:
                other = word[:index] + char + word[index + 1:]
                if other in pool and other not in previous:
                    previous[other] = word
                    queue.append(other)
    if target not in previous:
        return []
    path, node = [], target
    while node is not None:
        path.append(node)
        node = previous[node]
    return path[::-1]


def word_ladder_for(puzzle_date: date) -> tuple[str, str, list[str], int]:
    """(start, target, allowed-word bank, true optimal steps) for the day.

    The bank is deliberately small — _validate_ladder wants 6-15 words, and
    the client renders it as a word bank, so the full 1,745-word component
    can't be handed over. It is one shortest path plus neighbouring
    distractors, which keeps the puzzle solvable while leaving wrong turns to
    take. Distractors cannot make the puzzle shorter than the stored optimum:
    that was computed over the entire component, so no subset beats it.
    """
    puzzles = _ladder_puzzles()
    start, target, steps = puzzles[puzzle_date.toordinal() % len(puzzles)]
    pool = set(_ladder_words())

    path = _shortest_path(start, target, pool)
    bank = [word for word in path if word not in (start, target)]

    # Deterministic distractors: neighbours of the path that aren't on it,
    # walked in sorted order so the same date always yields the same puzzle.
    for word in path:
        for index in range(len(word)):
            for char in ascii_lowercase:
                other = word[:index] + char + word[index + 1:]
                if other in pool and other not in bank and other not in (start, target):
                    bank.append(other)
                if len(bank) >= LADDER_BANK_SIZE:
                    break
            if len(bank) >= LADDER_BANK_SIZE:
                break
        if len(bank) >= LADDER_BANK_SIZE:
            break

    return start.upper(), target.upper(), [word.upper() for word in bank], steps


def available() -> bool:
    """False if the data files didn't ship, so callers can fall back rather
    than fail the whole day's games."""
    try:
        return bool(_bee_puzzles()) and bool(_ladder_puzzles()) and bool(_bee_answers())
    except OSError as exc:
        logger.warning("Word list data unavailable: %s", exc)
        return False
