"""Guards the committed word lists in app/data/wordlists.

These files are generated by scripts/build_wordlists.py and then never
touched, so the risk isn't drift — it's shipping a file that was rebuilt with
a broken filter. Every check here re-derives the answer from the data rather
than trusting the counts the build wrote.
"""
from __future__ import annotations

from collections import deque
from pathlib import Path

import pytest

DATA = Path(__file__).resolve().parent.parent / "app" / "data" / "wordlists"


def load(name: str) -> list[str]:
    return [line for line in (DATA / name).read_text().splitlines() if not line.startswith("#")]


@pytest.fixture(scope="module")
def bee_answers() -> set[str]:
    return set(load("bee_answers.txt"))


@pytest.fixture(scope="module")
def bee_puzzles() -> list[tuple[str, str, int]]:
    return [(p, c, int(n)) for p, c, n in (row.split() for row in load("bee_puzzles.txt"))]


def test_every_bee_puzzle_is_playable(bee_answers, bee_puzzles):
    """Recomputes each puzzle's word list from scratch. A pangram is
    guaranteed because the letters are derived from one — this asserts the
    build didn't break that."""
    assert len(bee_puzzles) > 1000
    for pangram, centre, claimed in bee_puzzles[:400]:
        letters = set(pangram)
        assert len(letters) == 7, pangram
        assert centre in letters, (pangram, centre)
        words = [w for w in bee_answers if len(w) >= 4 and centre in w and set(w) <= letters]
        assert len(words) == claimed, (pangram, centre, len(words), claimed)
        assert any(set(w) == letters for w in words), f"no pangram for {pangram}"


def test_bee_puzzles_are_distinct_letter_sets(bee_puzzles):
    """ARCHING and CHAGRIN are one puzzle. Deduping by pangram string instead
    of letter set would serve the same seven letters several times a year."""
    assert len({frozenset(p) for p, _, _ in bee_puzzles}) == len(bee_puzzles)


def test_bee_puzzles_are_not_in_alphabetical_order(bee_puzzles):
    """The file is walked by date ordinal, so alphabetical order would hand
    consecutive days ABDICATE then ABDICATED."""
    heads = [p for p, _, _ in bee_puzzles[:50]]
    assert heads != sorted(heads)


def test_ladder_pairs_match_their_claimed_step_count():
    pool = set(load("ladder_words.txt"))
    pairs = [(a, b, int(n)) for a, b, n in (row.split() for row in load("ladder_puzzles.txt"))]
    assert len(pairs) > 500

    def shortest(start: str, target: str) -> int | None:
        queue, seen = deque([(start, 0)]), {start}
        while queue:
            word, steps = queue.popleft()
            if word == target:
                return steps
            for i in range(len(word)):
                for char in "abcdefghijklmnopqrstuvwxyz":
                    other = word[:i] + char + word[i + 1:]
                    if other in pool and other not in seen:
                        seen.add(other)
                        queue.append((other, steps + 1))
        return None

    for start, target, claimed in pairs[:150]:
        assert start in pool and target in pool
        assert shortest(start, target) == claimed, (start, target, claimed)


def test_wordle_answers_are_all_acceptable_guesses():
    """Otherwise the game rejects its own answer as an invalid word."""
    answers, guesses = set(load("wordle_answers.txt")), set(load("wordle_guesses.txt"))
    assert answers <= guesses
    assert all(len(w) == 5 and w.isalpha() and w.islower() for w in answers)


def test_no_slurs_survived_the_filter():
    # Imported by path: scripts/ is not a package, so a plain import of the
    # builder would depend on how pytest happened to set sys.path.
    import importlib.util

    builder_path = DATA.parent.parent.parent / "scripts" / "build_wordlists.py"
    spec = importlib.util.spec_from_file_location("build_wordlists", builder_path)
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    BLOCKED_SUBSTRINGS = builder.BLOCKED_SUBSTRINGS

    for name in ("bee_answers.txt", "wordle_answers.txt", "wordle_guesses.txt", "ladder_words.txt"):
        for word in load(name):
            assert not any(bad in word for bad in BLOCKED_SUBSTRINGS), f"{word} in {name}"
